### ISSUE TITLE
More space in right side 

### ISSUE THREAD

**Issue by codingkush** [The-Shivam-garg/BigB-E-learn-Websit-e#437] opened 2022-10-04 02:09 UTC
### Description

When i checked this site on pc so it wasn't  looking good...bcz there is a more space in right side of the website ...

Screenshot:---------->

![Screenshot_20221004-072121](https://user-images.githubusercontent.com/78756312/193719307-a6faac29-ebfb-4feb-b3ad-6e3617e91aa3.png)

![Screenshot_20221004-072156](https://user-images.githubusercontent.com/78756312/193719383-6dca52fc-c68b-4466-8864-efeb0760e08e.png)

**Comment by codingkush** [comment] 2022-10-04 02:10
Pls assign me this issue under hacktobetfest'22.... I'm new in hacktobetfest'22

**Comment by The-Shivam-garg** [comment] 2022-10-04 16:16
hey @codingkush , the issue is already mentioned in the issue list and assigned to someone else .please do check out the issue list before creating a new one

**Closed by The-Shivam-garg** 2022-10-04 16:16 UTC
Labels: bug, duplicate
