### ISSUE TITLE
[UX] <Improving usability of the website by improving the design and experience>

### ISSUE THREAD

**Issue by dattavelivela** [The-Shivam-garg/BigB-E-learn-Websit-e#422] opened 2022-06-26 05:52 UTC
### Description

BigB's Website design looks outdated. Buttons, Typography, Spacing, Color, and Landing pages of different pages are not consistent. It can be fixed by improving the website's user experience by revamping the design. 

### Screenshots
![Screenshot 2022-06-26 at 11-11-03 BigB](https://user-images.githubusercontent.com/97103375/175801436-631f89e5-e59c-4c13-8e5b-a0ec10c8af7a.png)

**Comment by dattavelivela** [comment] 2022-06-26 05:57
Hey @The-Shivam-garg  , can you please assign this issue to me so I can work on improving the design of the website to create a better user experience. I am sorry that I am not part of GSSoC22, I would like to contribute to this project.

**Comment by The-Shivam-garg** [comment] 2022-06-26 18:17
Hey @dattavelivela the issue is assigned to you  :)

**Closed** 2022-09-15 08:45 UTC
Labels: feature
